### ISSUE TITLE
EPIC: As Digiway I would like to integrate several real-time and static datastreams related in particular to the status of the hiking routes in the EUREGIO

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/opendatahub-content-api#534]
First datasets to be integrated:

- [ ] Hiking route E5, available via WFS service:
https://dservices3.arcgis.com/hG7UfxX49PQ8XkXh/arcgis/services/E5_Hiking_Route/WFSServer?service=wfs&request=getcapabilities
https://dservices3.arcgis.com/hG7UfxX49PQ8XkXh/arcgis/services/E5_Hiking_Route/WFSServer?service=wfs&request=getfeature&typename=E5_Hiking_Route:FC2_TARGET_ALL_WEBM_20250414_Append_4AGO

- [ ] Traffic Network E5, available via WFS service:
https://dservices3.arcgis.com/hG7UfxX49PQ8XkXh/arcgis/services/Traffic_Network/WFSServer?service=wfs&request=getcapabilities
https://dservices3.arcgis.com/hG7UfxX49PQ8XkXh/arcgis/services/Traffic_Network/WFSServer?service=wfs&request=getfeature&typename=Traffic_Network:FC1_TARGET_ALL_WEBM_20250414_AppendEx_Join_Add_grLaSy_4AGO

- [ ] Road network South Tyrol, available via WFS service:
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getCapabilities
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:LinksSequences-Labels (main roads)
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-MTB (official routes for mountain bikes)
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-Cycleways-Tyrol (cycling routes in North Tyrol)
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-HikingTrails (hiking trails)
https://geoservices1.civis.bz.it/geoserver/p_bz-TransportNetwork/ows?service=WFS&version=2.0.0&request=getFeature&typeName=p_bz-TransportNetwork:Routes-CyclewaysIntermunicipalPaths (intermunicipal cycling routes)

- [ ] Main road network Austria, available as GPKG export: 
https://open.gip.gv.at/ogd/B_gip_network_ogd.zip
https://open.gip.gv.at/ogd/C_gip_reference_ogd.zip
https://open.gip.gv.at/ogd/E_gip_localdata_ogd.zip
